apiVersion: packetprovider.k8s.io/v1alpha1
kind: PacketMachineProviderSpec
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: packetmachineproviderspec-sample
spec:
  # Add fields here
  foo: bar
