name: Cleanup
on:
  schedule:
    - cron: "0 */2 * * *" # TODO: Run every 4 hours to soak test, should be less frequent before merge (weekly/daily/???)
jobs:
  cleanup:
    name: Cleanup any orphaned CI Resources
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: ./.github/actions/setup-go
    - name: Run the cleanup tool
      run: go run ./cmd/ci-clean
      env:
        PACKET_API_KEY: ${{ secrets.PACKET_API_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
